#!/bin/sh

uptime=$(uptime -p | cut -c 4-)
user=$(whoami)
hostname=$(uname -a | cut -d' ' -f2)
kernel=$(uname -a | cut -d' ' -f2)
battery=$(cat /sys/class/power_supply/BAT1/capacity)
bat_stat=$(cat /sys/class/power_supply/BAT1/status)
date=$(date +'%a %b %d %l:%M %p')

player() {
    player_status=$(playerctl --player=%any,firefox,chromium status 2> /dev/null)

    if [ "$player_status" = "Playing" ]; then
        echo " $(playerctl metadata --player=%any,firefox,chromium --format '{{artist}} - {{title}}')"
    elif [ "$player_status" = "Paused" ]; then
        echo " $(playerctl metadata --player=%any,firefox,chromium --format 'Paused | {{artist}} - {{title}}')"
    else
        echo ""
    fi
}

# cpuPercent=$(mpstat | grep -A 5 "%idle" | tail -n 1 | awk -F " " '{print 100 -  $ 12}'a)

while IFS=':k '  read -r key val _; do
    case $key in
        MemTotal)
            mem_used=$((mem_used + val))
            mem_full=$val;;
        Shmem) mem_used=$((mem_used + val));;
        MemFree|Buffers|Cached|SReclaimable) mem_used=$((mem_used - val));;
    esac
done < /proc/meminfo
memPercent="$(echo 100 ${mem_used} \* ${mem_full} / p | dc)"


stats=$(column -t -s'\\' <<EOF
<b>Memory</b>\\${memPercent}%
<b>Battery</b>\\${battery}% ${bat_stat}
<b>Uptime</b>\\${uptime}
<b>Date</b>\\${date}
EOF
)

# get width of longest line in stats, minus formatting
width=$(echo "${stats}" | sed 's|<[^>]*>||g' | wc -L)


fortune=$(fortune -sn $(($width * 2)))
# fortune=$(fortune -sn 100 void)

line=$(printf '%0.s-' $(seq 1 $width))


title="${user}@${hostname}"

if [ "$(player)" = "" ]; then 
    body="$stats\n$line\n$fortune"
else
    body="$stats\n$line\n$(player)"
fi

# echo "${title}\n${body}"
notify-send "${title}" "${body}"
